# setup
setup: selflabel

model_kwargs:
   nheads: 1
   head: mlp
   features_dim: 128
   nclusters: 20

# ema
use_ema: False

# Threshold
confidence_threshold: 0.98

# Criterion
criterion: confidence-cross-entropy
criterion_kwargs:
    temperature: 0.1
    apply_class_balancing: True

# Model
backbone: resnet18
num_heads: 1

# Dataset
train_db_name: cifar-20
val_db_name: cifar-20
num_classes: 20
num_neighbors: 5

# Transformations
# augmentation_strategy: ours 
# augmentation_kwargs:
#    crop_size: 32
#    normalize:
#       mean: [0.5071, 0.4867, 0.4408]
#       std: [0.2675, 0.2565, 0.2761]
#    num_strong_augs: 4
#    cutout_kwargs:
#      n_holes: 1
#      length: 16
#      random: True

# transformation_kwargs:
#    crop_size: 32
#    normalize:
#       mean: [0.5071, 0.4867, 0.4408]
#       std: [0.2675, 0.2565, 0.2761]
augmentation_strategy: both
augmentation_kwargs:
   random_resized_crop:
      size: 32
      scale: [0.2, 1.0]
   color_jitter_random_apply:
      p: 0.8
   color_jitter:
      brightness: 0.4
      contrast: 0.4
      saturation: 0.4
      hue: 0.1
   random_grayscale: 
      p: 0.2
   normalize:
      mean: [0.4914, 0.4822, 0.4465]
      std: [0.2023, 0.1994, 0.2010]
strong_augmentation_kwargs:
   num_strong_augs: 5
   prob_strong_augs: 10

transformation_kwargs:
   resize: 40
   crop_size: 32
   normalize:
      mean: [0.4914, 0.4822, 0.4465]
      std: [0.2023, 0.1994, 0.2010]

# Hyperparameters
epochs: 400
beta: 1.0
optimizer: adam
optimizer_kwargs:
   lr: 0.0001
   weight_decay: 0.0001
batch_size: 1024
num_workers: 8

# Scheduler
scheduler: constant
