# setup
setup: selflabel

model_kwargs:
   head: mlp
   features_dim: 128
   nheads: 1
   nclusters: 10

# ema
use_ema: False

# Threshold
confidence_threshold: 0.98

# Criterion
criterion: confidence-cross-entropy
criterion_kwargs:
   temperature: 0.1 
   apply_class_balancing: True

# Model
backbone: resnet18
num_heads: 1

# Dataset
train_db_name: cifar-10
val_db_name: cifar-10
num_classes: 10
num_neighbors: 5

# Transformations
augmentation_strategy: both
augmentation_kwargs:
   random_resized_crop:
      size: 32
      scale: [0.2, 1.0]
   color_jitter_random_apply:
      p: 0.8
   color_jitter:
      brightness: 0.4
      contrast: 0.4
      saturation: 0.4
      hue: 0.1
   random_grayscale: 
      p: 0.2
   normalize:
      mean: [0.4914, 0.4822, 0.4465]
      std: [0.2023, 0.1994, 0.2010]
strong_augmentation_kwargs:
   num_strong_augs: 5
   prob_strong_augs: 10

transformation_kwargs:
   resize: 40
   crop_size: 32
   normalize:
      mean: [0.4914, 0.4822, 0.4465]
      std: [0.2023, 0.1994, 0.2010]

# Hyperparameters
epochs: 400
beta: 1.0

batch_size: 1024
num_workers: 8
optimizer: adam
optimizer_kwargs:
   lr: 0.0001
   weight_decay: 0.0001
# Scheduler
scheduler: constant
